version: '3.8'

services:
  repair-service:
    build: .
    container_name: repair-service-app
    ports:
      - "3000:3000"
    volumes:
      - ./repair_service.db:/app/repair_service.db
    restart: always
    environment:
      - NODE_ENV=production
